### ISSUE TITLE
Clean up error message/behavior on double tag

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#1014]
Uploading a run (and presumably any entity) with the same tag twice produces a stack trace:
```python
import openml
from sklearn.tree import DecisionTreeClassifier

run = openml.runs.run_model_on_task(DecisionTreeClassifier(), 59)
print('Run is not yet uploaded:', run.id == None)
run.tags = ["a", "a"]
run.publish()
```
output:
```
Traceback (most recent call last):
  File "E:\repositories\automlbenchmark\venv\lib\site-packages\openml\_api_calls.py", line 219, in __parse_server_exception
    server_exception = xmltodict.parse(response.text)
  File "E:\repositories\automlbenchmark\venv\lib\site-packages\xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: junk after document element: line 6, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/repositories/automlbenchmark/double_tag_run.py", line 9, in <module>
    run.publish()
  File "E:\repositories\automlbenchmark\venv\lib\site-packages\openml\base.py", line 130, in publish
    response_text = openml._api_calls._perform_api_call(
  File "E:\repositories\automlbenchmark\venv\lib\site-packages\openml\_api_calls.py", line 62, in _perform_api_call
    __check_response(response, url, file_elements)
  File "E:\repositories\automlbenchmark\venv\lib\site-packages\openml\_api_calls.py", line 143, in __check_response
    raise __parse_server_exception(response, url, file_elements=file_elements)
  File "E:\repositories\automlbenchmark\venv\lib\site-packages\openml\_api_calls.py", line 223, in __parse_server_exception
    raise OpenMLServerError(
openml.exceptions.OpenMLServerError: Unexpected server error when calling https://www.openml.org/api/v1/xml/run/. Please contact the developers!
Status code: 500
<oml:error xmlns:oml="http://openml.org/openml">
	<oml:code>473</oml:code>
	<oml:message>Entity already tagged by this tag. </oml:message>
		<oml:additional_information>id=10559752; tag=a</oml:additional_information>
	</oml:error>
<oml:upload_run xmlns:oml="http://openml.org/openml">
	<oml:run_id>10559752</oml:run_id>
	</oml:upload_run>

Process finished with exit code 1
```

The key information is present in the stack trace:
```
<oml:message>Entity already tagged by this tag. </oml:message>
		<oml:additional_information>id=10559752; tag=a</oml:additional_information>
```

But it's alongside rubbish like
```
openml.exceptions.OpenMLServerError: Unexpected server error when calling https://www.openml.org/api/v1/xml/run/. Please contact the developers!
```

We should probably produce just one properly formatted error, or automatically detect this before upload. After detection (but before upload) we could either error out, or remove duplicate entries and upload with a warning. The latter would be my preferred behavior (given that tags can be modified after upload anyway). Either way I think the current behavior should be improved upon.

**Comment by mfeurer** [comment]
An `ExpatError` is usually the symptom of an overloaded server. We do not retry on that because so far we haven't figured out if this means that potentially something on the server was done/changed.

**Comment by PGijsbers** [comment]
But this is reliably reproducible, alternating a correct upload (one tag) and a bad one (duplicate tag), the correct one always succeeds without error while the other produces the `ExpatError` The `oml:message` is also quite clear. Both indicate to me it is not an overloaded server.
Perhaps we should rather open an issue on the server repo to make sure they return the right error for this scenario?

And if they do, and we can produce a nicer error in `openml-python`, should we still try to catch this on our end? It's nice if we can prevent this from happening in the first place and not ask the server to do something we know it should not allow.

**Comment by mfeurer** [comment]
>  Perhaps we should rather open an issue on the server repo to make sure they return the right error for this scenario?

Yes, it would be great if you could do so. The error is that there's no closing `</oml:error>` tag in the XML so it cannot be parsed. That means that we show the 500 error as we cannot show anything better as we cannot parse the original error, but also show that to give at least some info on what went wrong in the first place.

> should we still try to catch this on our end

Do you mean creating a specific Exception class or just parsing the XML error description and making it nicer? It would be great if that could be done in general for all messages, but I'm not sure if that's possible.

**Comment by PGijsbers** [comment]
> Do you mean creating a specific Exception class or just parsing the XML error description and making it nicer? It would be great if that could be done in general for all messages, but I'm not sure if that's possible.
 
 I actually meant having a check before upload to check there are no duplicates in tags (`list(tags) == set(tags)`). I think general xsd validation will be easier when we use the swagger descriptions?

**Comment by mfeurer** [comment]
> I actually meant having a check before upload to check there are no duplicates in tags

Yes, I think that could be done. Or we just cast to set and upload that?

> Would XSD help here in detecting duplicates?

**Comment by PGijsbers** [comment]
As far as I am aware, xsd validation would not catch duplicates. It would help with other issues like checking tags are `oml:system_string128` before upload.

> Or we just cast to set and upload that?

Yes I think that's cleanest. Only question is whether or not a warning should be given (since we're changing user input).

**Comment by mfeurer** [comment]
> It would help with other issues like checking tags are oml:system_string128 before upload.

Yes, definitely. I think we have an issue for that (at least for models/flows).

> Yes I think that's cleanest. Only question is whether or not a warning should be given (since we're changing user input).

Warning would be fine.
