### ISSUE TITLE
Cannot import openml due to write-only cache directory

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#1099]
#### Description

Cannot import openml due to write-only cache directory.

#### Steps/Code to Reproduce
```
import openml
```

Obviously, this requires one to have a read-only filesystem to trigger this error.

#### Expected Results
No error.

#### Actual Results
```
Traceback (most recent call last):
  File "runbenchmark.py", line 9, in <module>
    import amlb.logger
  File "/bench/amlb/__init__.py", line 7, in <module>
    from .resources import Resources
  File "/bench/amlb/resources.py", line 12, in <module>
    from amlb.benchmarks.parser import benchmark_load
  File "/bench/amlb/benchmarks/parser.py", line 3, in <module>
    from .openml import is_openml_benchmark, load_oml_benchmark
  File "/bench/amlb/benchmarks/openml.py", line 4, in <module>
    import openml
  File "/bench/venv/lib/python3.7/site-packages/openml/__init__.py", line 20, in <module>
    from . import _api_calls
  File "/bench/venv/lib/python3.7/site-packages/openml/_api_calls.py", line 17, in <module>
    from . import config
  File "/bench/venv/lib/python3.7/site-packages/openml/config.py", line 384, in <module>
    _setup()
  File "/bench/venv/lib/python3.7/site-packages/openml/config.py", line 266, in _setup
    os.makedirs(cache_directory, exist_ok=True)
  File "/usr/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/work'
```

#### Versions
OpenML 0.12.2

**Comment by PGijsbers** [comment]
You specify "No error." as expected result. By default any download is stored in cache, and I don't know which, if any, of the writes can handle errors caused by a read-only directory. What is the expected behavior here, to allow the use of `openml` but only for objects which are already in the cache? Do allow users to use openml without writing to cache, but downloading new datasets and handle it entirely in memory?

In either case I would probably expect at least a warning.

**Comment by mfeurer** [comment]
Ah, I see the problem with my issue post. So the cache directory was supposed to be `/work/partition2/feurerm-openml/`, and I have write access to `feurerm-openml`. The issue is that the first part, `/work` is a read-only file system, but `os.makedirs` tries to write there.

My proposed solution would be to raise a warning like we do for the permission error.
