### ISSUE TITLE
Upload of high-dimensional datasets fails when exceeding moderate sample size

### ISSUE THREAD

**Issue by dnwissel** [openml/openml-python#1156]
#### Description
I am trying to upload some high-dimensional datasets with p >> n (n generally 100-800, p usually around ~80,000). Now while some of the smaller datasets have uploaded fine, I continually run into issues trying this with larger datasets (starts to happen around ~200+ samples). 

Since I cannot reproduce this quite so easily with off-the-shelf data, I will just share the dataset in question: https://ibm.ent.box.com/v/survboard-meta/folder/165089189759.

#### Steps/Code to Reproduce

```python
import pandas as pd
from openml.datasets.functions import create_dataset

data = pd.read_csv(
    "BLCA_data_complete_modalities_preprocessed.csv"
)
openml_dataset = create_dataset(
    name="BLCA-test",
    description="Lorem ipsum.",
    contributor=None,
    collection_date=None,
    language="English",
    licence="MIT",
    default_target_attribute="OS,OS_days",
    row_id_attribute=None,
    ignore_attribute="patient_id",
    citation=None,
    attributes="auto",
    data=data,
    version_label="0.1",
)
openml_dataset.publish()

```

#### Expected Results
The dataset is sucessfully uploaded.

#### Actual Results
```
Traceback (most recent call last):
  File "/Users/slightlier/miniforge3/envs/survival_benchmark/lib/python3.9/site-packages/openml/_api_calls.py", line 237, in _send_request
    __check_response(response=response, url=url, file_elements=files)
  File "/Users/slightlier/miniforge3/envs/survival_benchmark/lib/python3.9/site-packages/openml/_api_calls.py", line 284, in __check_response
    raise __parse_server_exception(response, url, file_elements=file_elements)
  File "/Users/slightlier/miniforge3/envs/survival_benchmark/lib/python3.9/site-packages/openml/_api_calls.py", line 298, in __parse_server_exception
    server_exception = xmltodict.parse(response.text)
  File "/Users/slightlier/miniforge3/envs/survival_benchmark/lib/python3.9/site-packages/xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/slightlier/survival_benchmark/publish.py", line 34, in <module>
    sys.exit(main())
  File "/Users/slightlier/survival_benchmark/publish.py", line 29, in main
    openml_dataset.publish()
  File "/Users/slightlier/miniforge3/envs/survival_benchmark/lib/python3.9/site-packages/openml/base.py", line 130, in publish
    response_text = openml._api_calls._perform_api_call(
  File "/Users/slightlier/miniforge3/envs/survival_benchmark/lib/python3.9/site-packages/openml/_api_calls.py", line 65, in _perform_api_call
    response = _read_url_files(url, data=data, file_elements=file_elements)
  File "/Users/slightlier/miniforge3/envs/survival_benchmark/lib/python3.9/site-packages/openml/_api_calls.py", line 197, in _read_url_files
    response = _send_request(request_method="post", url=url, data=data, files=file_elements,)
  File "/Users/slightlier/miniforge3/envs/survival_benchmark/lib/python3.9/site-packages/openml/_api_calls.py", line 257, in _send_request
    raise OpenMLServerError(
openml.exceptions.OpenMLServerError: Unexpected server error when calling https://www.openml.org/api/v1/xml/data/. Please contact the developers!
Status code: 500
```
#### Versions
```
>>> import platform; print(platform.platform())
macOS-12.2.1-arm64-arm-64bit
>>> import sys; print("Python", sys.version)
Python 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:55:15) 
[Clang 11.0.0 ]
>>> import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import sklearn; print("Scikit-Learn", sklearn.__version__)
import openml; print("OpenML", openml.__version__)
NumPy 1.21.5
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.8.0
>>> import sklearn; print("Scikit-Learn", sklearn.__version__)
Scikit-Learn 1.0.2
>>> import openml; print("OpenML", openml.__version__)
OpenML 0.12.2
```

I had a look at other issues (particularly #746 and #1010), but they seem to be happening at much larger file sizes (my file above is "only" about 280 MB). In an unrelated issue, it was stated that an `ExpatError` is usually the symptom of an overloaded server - if this is the case, is there anything I can do to avoid this?

Any help is very much appreciated, happy to provide further details where needed! Thank you!

**Comment by staru09** [comment]
Is this still open to work?
