### ISSUE TITLE
Parquet error when calling ```get_data()```

### ISSUE THREAD

**Issue by Wman1001** [openml/openml-python#1279]
#### Description
When calling ```get_data()``` on a data set not yet present in my cache directory, I get a parquet error

#### Steps/Code to Reproduce

```
import openml
dataset = openml.datasets.get_dataset(179)
X, y, categorical_attribute, attribute_names = dataset.get_data(target=dataset.default_target_attribute)
```

#### Expected Results
 Retrieve the data set

#### Actual Results
Traceback (most recent call last):
  File "/home/TUE/20174868/miniconda3/envs/thesis_env/lib/python3.11/site-packages/openml/datasets/dataset.py", line 489, in _cache_compressed_file_from_file
    data = pd.read_parquet(data_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TUE/20174868/miniconda3/envs/thesis_env/lib/python3.11/site-packages/pandas/io/parquet.py", line 503, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/TUE/20174868/miniconda3/envs/thesis_env/lib/python3.11/site-packages/pandas/io/parquet.py", line 251, in read
    result = self.api.parquet.read_table(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TUE/20174868/miniconda3/envs/thesis_env/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 2926, in read_table
    dataset = _ParquetDatasetV2(
              ^^^^^^^^^^^^^^^^^^
  File "/home/TUE/20174868/miniconda3/envs/thesis_env/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 2466, in __init__
    [fragment], schema=schema or fragment.physical_schema,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_dataset.pyx", line 1004, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not open Parquet input source '<Buffer>': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/TUE/20174868/hpc_files/SBPort/experiment_runner.py", line 494, in <module>
    main()
  File "/home/TUE/20174868/hpc_files/SBPort/experiment_runner.py", line 476, in main
    experiment_runner.run_gama(max_total_time = 600, max_eval_time = 360)
  File "/home/TUE/20174868/hpc_files/SBPort/experiment_runner.py", line 279, in run_gama
    X, y, categorical_indicator = prepare_openml_for_inf(dataset_id)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TUE/20174868/hpc_files/SBPort/utils.py", line 69, in prepare_openml_for_inf
    X, y, categorical_indicator, attribute_names = dataset.get_data(
                                                   ^^^^^^^^^^^^^^^^^
  File "/home/TUE/20174868/miniconda3/envs/thesis_env/lib/python3.11/site-packages/openml/datasets/dataset.py", line 704, in get_data
    data, categorical, attribute_names = self._load_data()
                                         ^^^^^^^^^^^^^^^^^
  File "/home/TUE/20174868/miniconda3/envs/thesis_env/lib/python3.11/site-packages/openml/datasets/dataset.py", line 529, in _load_data
    return self._cache_compressed_file_from_file(file_to_load)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TUE/20174868/miniconda3/envs/thesis_env/lib/python3.11/site-packages/openml/datasets/dataset.py", line 491, in _cache_compressed_file_from_file
    raise Exception(f"File: {data_file}") from e
Exception: File: /home/TUE/20174868/.cache/openml/org/openml/www/datasets/179/dataset_179.pq 

#### Versions
Linux-4.4.0-210-generic-x86_64-with-glibc2.23
Python 3.11.3 [GCC 11.2.0]
Numpy 1.24.3
SciPy 1.10.1
SciKit-Learn 1.2.2
OpenML 0.13.1

**Comment by prabhant** [comment]
Hi, 

The issue is caused by an error from our side, We are in the process of fixing the issue.

**Comment by Wman1001** [comment]
@prabhant Thank you for the quick reply, do you have any time indication when this will be fixed?

**Comment by PGijsbers** [comment]
I asked someone that knows the give an update. But in the mean time, make sure to clean your cache (of parquet files).

**Comment by PGijsbers** [comment]
It should work now (provided you don’t have cached corrupted pq files). Unfortunately I can’t test it myself right now.

**Comment by Wman1001** [comment]
I tested this out for a data set (not present in my cache), and it indeed works. Thank you!
