### ISSUE TITLE
Downloading task throws a KeyError

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#168]
Simply downloading a task is not possible right now:

```
from openml import datasets, tasks, runs
task = tasks.get_task(10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "openml/tasks/functions.py", line 202, in get_task
    task = _create_task_from_xml(fh.read())
  File "openml/tasks/functions.py", line 249, in _create_task_from_xml
    dic["oml:task_id"], dic['oml:task_type_id'], dic["oml:task_type"],
KeyError: 'oml:task_type_id'
```

**Comment by joaquinvanschoren** [comment]
Sorry, this error went away when I cleared my cache.
