### ISSUE TITLE
OpenMLFlow._ensure_flow_exists does not work together with OpenMLFlow.publish()

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#173]
```
Traceback (most recent call last):
  File "/media/matthias/Data/work/github/python/svm.py", line 30, in <module>
    openml.runs.run_task(task, learners[learner])
  File "/media/matthias/Data/work/github/python/openml/runs/functions.py", line 44, in run_task
    flow_id = flow._ensure_flow_exists()
  File "/media/matthias/Data/work/github/python/openml/flows/flow.py", line 112, in _ensure_flow_exists
    return_code, response_xml = self.publish()
TypeError: 'OpenMLFlow' object is not iterable
```

because `self.publish` returns `self` now.

**Comment by mfeurer** [comment]
Was fixed in PR #167.
