### ISSUE TITLE
ARFF parse error for dataset 1037

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#287]
Seems like the python ARFF parser is confused by comments on attributes, like this one:
@attribute label {-1,1} %{<=50K, >50K}

How should we deal with this?

Reproduce:
```
import openml
openml.datasets.get_dataset(1037).qualities
```

yields:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joa/anaconda/lib/python3.5/site-packages/openml/datasets/functions.py", line 289, in get_dataset
    dataset = _create_dataset_from_description(description, features, qualities, arff_file)
  File "/Users/joa/anaconda/lib/python3.5/site-packages/openml/datasets/functions.py", line 528, in _create_dataset_from_description
    qualities=qualities)
  File "/Users/joa/anaconda/lib/python3.5/site-packages/openml/datasets/dataset.py", line 106, in __init__
    data = self._get_arff(self.format)
  File "/Users/joa/anaconda/lib/python3.5/site-packages/openml/datasets/dataset.py", line 185, in _get_arff
    return decode_arff(fh)
  File "/Users/joa/anaconda/lib/python3.5/site-packages/openml/datasets/dataset.py", line 178, in decode_arff
    return_type=return_type)
  File "/Users/joa/anaconda/lib/python3.5/site-packages/arff.py", line 743, in decode
    raise e
  File "/Users/joa/anaconda/lib/python3.5/site-packages/arff.py", line 739, in decode
    matrix_type=return_type)
  File "/Users/joa/anaconda/lib/python3.5/site-packages/arff.py", line 677, in _decode
    attr = self._decode_attribute(row)
  File "/Users/joa/anaconda/lib/python3.5/site-packages/arff.py", line 621, in _decode_attribute
    raise BadAttributeType()
arff.BadAttributeType: Bad @ATTRIBUTE type, at line 36.
```

**Comment by janvanrijn** [comment]
Although the ARFF specification is not very clearly documented, this seems
to be in line with it:
"Lines that begin with a % are comments."
So we should probably give an upload error when an arff file contains this

2017-07-31 15:44 GMT+02:00 Joaquin Vanschoren <notifications@github.com>:

**Comment by joaquinvanschoren** [comment]
It's apparently not uncommon.
Also happens for 1039, 1042, 1057, 1074

Even so, what do we do with the active datasets already on OpenML, which have WEKA and R experiments. Should we edit the ARFF files to remove the end-of-line comments?

**Comment by mfeurer** [comment]
I do also interpret the arff specification as this being invalid (as it is not defined). I recall that we replaced some datasets with 'fixed' versions two or three years ago. A different solution to fixing the current datasets would be to ask the maintainers of the arff specification to update their specification (although this would make the parsing a bit harder + someone would have to implement it).

**Comment by mfeurer** [comment]
We're now handling this in https://github.com/openml/OpenML/issues/476.

**Comment by MaxHeuillet** [comment]
This still happens on data ids: 41707, 41708, 41709,41710,41711,41712

When using this code:

```
dataset = openml.datasets.get_dataset(idx)
X, y, categorical_indicator, attribute_names = dataset.get_data(dataset_format='dataframe', target=dataset.default_target_attribute)
```

**Comment by mfeurer** [comment]
Reopening this so we check those datasets.

**Comment by mfeurer** [comment]
Closing this again as the issue mentioned by @MaxHeuillet is not related to arff being ill-formatted, but the arff parser not supporting the date datatype. Please see #942 on progress with this issue.
