### ISSUE TITLE
Illegal filter input

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#419]
Apparently, something changed on OpenML.org. The unit tests show this:
```
Traceback (most recent call last):
  File "/home/travis/build/openml/openml-python/tests/test_setups/test_setup_functions.py", line 141, in test_list_setups_empty
    setups = openml.setups.list_setups(setup=[-1])
  File "/home/travis/build/openml/openml-python/openml/setups/functions.py", line 143, in list_setups
    return _list_setups(api_call)
  File "/home/travis/build/openml/openml-python/openml/setups/functions.py", line 150, in _list_setups
    xml_string = openml._api_calls._perform_api_call(api_call)
  File "/home/travis/build/openml/openml-python/openml/_api_calls.py", line 53, in _perform_api_call
    return _read_url(url, data)
  File "/home/travis/build/openml/openml-python/openml/_api_calls.py", line 120, in _read_url
    raise _parse_server_exception(response, url=url)
OpenMLServerException: Illegal filter input.
```

**Comment by janvanrijn** [comment]
Last week I indeed added additional input checks that the required inputs are in fact an unsigned integer (0 or higher).

Changing the value to 0 would fix the problem. Sorry for the inconvenience

**Comment by janvanrijn** [comment]
I will fix this in PR #399

**Comment by janvanrijn** [comment]
Oops, I was wrong. At the moment, a filter on setups with value 0 is not accepted by the server (due to a bug it ignores the filter). Pushed a fix in the OpenML repo. Will be fixed after.

**Comment by mfeurer** [comment]
Python unit tests work again. Closing this one now.
