### ISSUE TITLE
Authentication issue with get request

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#471]
MWE:
```
import openml
import openmlcontrib
import unittest


class TestMiscFunctions(unittest.TestCase):

    def setUp(self):
        self.test_server = "https://test.openml.org/api/v1/xml/"

    def test_obtain_setups_by_ids(self):
        openml.config.server = self.test_server
        setup_ids = range(1, 30)
        setups = openmlcontrib.setups.obtain_setups_by_ids(setup_ids, limit=7)
        self.assertEquals(set(setups.keys(), set(setup_ids)))
```

gives the following stacktrace:
```
FAILED (errors=2)

Error
Traceback (most recent call last):
  File "/home/janvanrijn/anaconda3/envs/openmlpimp/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/janvanrijn/anaconda3/envs/openmlpimp/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/janvanrijn/projects/openml-python-contrib/tests/test_setups/test_setups_functions.py", line 20, in test_obtain_setups_by_ids_incomplete
    openmlcontrib.setups.obtain_setups_by_ids(setup_ids, limit=5)
  File "/home/janvanrijn/projects/openml-python-contrib/openmlcontrib/setups/functions.py", line 96, in obtain_setups_by_ids
    setups_batch = openml.setups.list_setups(setup=setup_ids[offset:offset+limit])
  File "/home/janvanrijn/projects/openml-python/openml/setups/functions.py", line 128, in list_setups
    flow=flow, tag=tag, setup=setup, batch_size=1000)  #batch size for setups is lower
  File "/home/janvanrijn/projects/openml-python/openml/utils.py", line 150, in _list_all
    **active_filters
  File "/home/janvanrijn/projects/openml-python/openml/setups/functions.py", line 157, in _list_setups
    return __list_setups(api_call)
  File "/home/janvanrijn/projects/openml-python/openml/setups/functions.py", line 162, in __list_setups
    xml_string = openml._api_calls._perform_api_call(api_call)
  File "/home/janvanrijn/projects/openml-python/openml/_api_calls.py", line 53, in _perform_api_call
    return _read_url(url, data)
  File "/home/janvanrijn/projects/openml-python/openml/_api_calls.py", line 122, in _read_url
    raise _parse_server_exception(response, url=url)
openml.exceptions.OpenMLServerException: https://test.openml.org/api/v1/xml/setup/list/setup/0,1,2,3,4/limit/1000/offset/0 returned code 103: Authentication failed
```
Whereas retrieving the URL by hand succeeds

**Comment by mfeurer** [comment]
I cannot reproduce this on the development branch with the following code:
```
import collections
import openml


def obtain_setups_by_ids(setup_ids, require_all=True, limit=250):
    """
    Obtains a list of setups by id. Because the
    Parameters
    ----------
    setup_ids : list[int]
        list of setups to obtain
    require_all : bool
        if set to True, the list of requested setups is required to
        be complete (and an error is thrown if not)
    limit : int
        The number of setups to obtain per call
        (lower numbers avoid long URLs, but take longer)
    Returns
    -------
    The dict of setups
    """
    if not isinstance(setup_ids, collections.Iterable):
        raise ValueError()
    for val in setup_ids:
        if not isinstance(val, int):
            raise ValueError()

    setups = {}
    offset = 0
    setup_ids = list(setup_ids)
    while True:
        setups_batch = openml.setups.list_setups(setup=setup_ids[offset:offset + limit])
        setups.update(setups_batch)

        offset += limit
        if offset >= len(setup_ids):
            break
    if require_all:
        missing = set(setup_ids) - set(setups.keys())
        if set(setup_ids) != set(setups.keys()):
            raise ValueError('Did not get all setup ids. Missing: %s' % missing)

    return setups

test_server = "https://test.openml.org/api/v1/xml/"
openml.config.server = test_server
setup_ids = range(1, 30)
setups = obtain_setups_by_ids(setup_ids, limit=7)
print(setups)
```

**Comment by janvanrijn** [comment]
You are right.
