### ISSUE TITLE
Flows and Runs Documentation requires develop branch of repo to work

### ISSUE THREAD

**Issue by pfontana3w2** [openml/openml-python#703]
#### Description
The documentation on flows and runs https://openml.github.io/openml-python/develop/examples/flows_and_runs_tutorial.html requires the develop branch of the code and will not work with the master brach available through a pip install.

When running it with the version available from pip openml, it crashes with an error.

The first code block is taking straight from python/develop/examples/flows_and_runs_tutorial.html , while the second is code I have adapted from other documentation.

#### Steps/Code to Reproduce
```bash
pip install openml
```

```python
import openml
from pprint import pprint
from sklearn import ensemble, neighbors, preprocessing, pipeline, tree

openml.config.start_using_configuration_for_example()
# NOTE: We are using dataset 68 from the test server: https://test.openml.org/d/68
dataset = openml.datasets.get_dataset(68)
X, y, categorical_indicator, attribute_names = dataset.get_data(
    dataset_format='array',
    target=dataset.default_target_attribute
)
clf = neighbors.KNeighborsClassifier(n_neighbors=1)
clf.fit(X, y)

dataset = openml.datasets.get_dataset(17)
X, y, categorical_indicator, attribute_names = dataset.get_data(
    dataset_format='array',
    target=dataset.default_target_attribute
)
print("Categorical features: {}".format(categorical_indicator))
enc = preprocessing.OneHotEncoder(categorical_features=categorical_indicator)
X = enc.fit_transform(X)
clf.fit(X, y)
```

Code block 2

```python
import openml
import sklearn.preprocessing
import sklearn.tree
import sklearn.pipeline
import pandas as pd
import pprint

# my API Key


clf = sklearn.pipeline.Pipeline(
    steps=[
        ('imputer', sklearn.preprocessing.Imputer()),
        ('estimator', sklearn.tree.DecisionTreeClassifier())
    ]
)

task = openml.tasks.get_task(31)
run = openml.runs.run_model_on_task(clf, task, avoid_duplicate_runs=False, upload_flow=False)
```

tasks = openml.tasks.list_tasks(task_type_id=1)
tasks = pd.DataFrame.from_dict(tasks, orient='index')
```
<!--
Example:
```python
import openml
openml.flows.get_flow(1)
```
If the code is too long, feel free to put it in a public gist and link
it in the issue: https://gist.github.com
-->

#### Expected Results

Should work without an error for both code blocks.

Output of Code block 1 when run from version in develop branch

```
Categorical features: [True, False, True, True, False, True, True, False, True, True, False, True, False, True, True, False, True, False, True, True]
/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)
Out[2]: 
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')
```

Output of code block 2 when run from version in develop branch. I'm using an old Imputer class so the warning can be ignored.

```
/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
```

#### Actual Results

For code block 1

```
Traceback (most recent call last):
  File "/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-5c95a6521452>", line 5, in <module>
    openml.config.start_using_configuration_for_example()
AttributeError: module 'openml.config' has no attribute 'start_using_configuration_for_example'
```

For Code block 2
```
/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
Traceback (most recent call last):
  File "/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-fa59a41ce3c4>", line 20, in <module>
    run = openml.runs.run_model_on_task(clf, task, avoid_duplicate_runs=False, upload_flow=False)
TypeError: run_model_on_task() got an unexpected keyword argument 'upload_flow'
```

#### Versions

Darwin-18.6.0-x86_64-i386-64bit
Python 3.6.8 (default, Mar 20 2019, 16:36:17) 
[GCC 4.2.1 Compatible Clang 6.0.0 (tags/RELEASE_600/final)]
NumPy 1.16.2
SciPy 1.2.1
Scikit-Learn 0.20.3
OpenML 0.8.0

**Comment by mfeurer** [comment]
Please use the documentation at https://openml.github.io/openml-python/master/ for the master branch, you're currently using https://openml.github.io/openml-python/develop/.

**Comment by pfontana3w2** [comment]
Thank you for taking the time to respond.
