### ISSUE TITLE
Introductory examples with running pipelines require "from" import syntax to work

### ISSUE THREAD

**Issue by pfontana3w2** [openml/openml-python#704]
#### Description
When I run the introductory code in the documentation, https://openml.github.io/openml-python/develop/ it works fine but if I use

```python
import sklearn.preprocessing
import sklearn.tree
import sklearn.pipeline,
```

I get instead:

```python
ValueError: No extension registered which can handle model: <openml.tasks.task.OpenMLClassificationTask object at 0x107612438>
```

#### Steps/Code to Reproduce
```
import openml
import sklearn.preprocessing
import sklearn.tree
import sklearn.pipeline

# Set the OpenML API Key which is required to upload your runs.
# You can get your own API by signing up to OpenML.org.
openml.config.apikey = 'ABC'

# Define a scikit-learn classifier or pipeline
clf = sklearn.pipeline.Pipeline(
    steps=[
        ('imputer', sklearn.preprocessing.Imputer()),
        ('estimator', sklearn.tree.DecisionTreeClassifier())
    ]
)
# Download the OpenML task for the german credit card dataset with 10-fold
# cross-validation.
task = openml.tasks.get_task(31)
# Run the scikit-learn model on the task.
run = openml.runs.run_model_on_task(clf, task)
```
#### Expected Results

No error is thrown.

#### Actual Results

```python
Traceback (most recent call last):
  File "/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-a0d0c88d4e8e>", line 3, in <module>
    run = openml.runs.run_model_on_task(task, clf)
  File "/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/openml/runs/functions.py", line 81, in run_model_on_task
    extension = get_extension_by_model(model, raise_if_no_extension=True)
  File "/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/openml/extensions/functions.py", line 93, in get_extension_by_model
    raise ValueError('No extension registered which can handle model: {}'.format(model))
ValueError: No extension registered which can handle model: <openml.tasks.task.OpenMLClassificationTask object at 0x107612438>
```

#### Versions

Darwin-18.6.0-x86_64-i386-64bit
Python 3.6.8 (default, Mar 20 2019, 16:36:17) 
[GCC 4.2.1 Compatible Clang 6.0.0 (tags/RELEASE_600/final)]
NumPy 1.16.2
SciPy 1.2.1
Scikit-Learn 0.20.3
OpenML 0.8.0

**Comment by pfontana3w2** [comment]
I now found the error on my side. I reversed the model and the tasks in the `openl.runs.run_model_on_task`. The code is fine. Closing issue.
