### ISSUE TITLE
Unit tests failing

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#759]
Due to wheels not being properly downloaded. 

This is an issue that appeared with the upgrade to Python3.7.4 (https://travis-ci.org/openml/openml-python/builds/570006525) from Python3.7.3 (https://travis-ci.org/openml/openml-python/builds/569541467).

Minimal example:
```
cd /tmp
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
chmod +x miniconda.sh && ./miniconda.sh -b -p /tmp/miniconda
export PATH=/tmp/miniconda/bin:$PATH
conda update --yes conda
conda create -n testenv --yes python=3.7 pip
source activate testenv
conda list
which pip
pip install pandas -v
```
Output of the last command:
```
(testenv) feurerm@mllap04:/tmp$ pip install pandas -v
7.4.0
Created temporary directory: /tmp/pip-ephem-wheel-cache-_4fq2p9s
Created temporary directory: /tmp/pip-req-tracker-s667qpdr
Created requirements tracker '/tmp/pip-req-tracker-s667qpdr'
Created temporary directory: /tmp/pip-install-dwr0_w9p
Collecting pandas
  1 location(s) to search for versions of pandas:
  * https://pypi.org/simple/pandas/
  Getting page https://pypi.org/simple/pandas/
  Looking up "https://pypi.org/simple/pandas/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/pandas/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/pandas/
    Found link https://files.pythonhosted.org/packages/b4/8e/057ebd80a3b6dcda154dd6878744fc5549832a484e72bc4189b8d782be75/pandas-0.1.tar.gz#sha256=8d65c67df35e181997c6ede3a0721f8989d1928c9be4fc91ecd5ced311ecd3b6 (from https://pypi.org/simple/pandas/), version: 0.1
    Skipping link https://files.pythonhosted.org/packages/c4/bc/e5e0373d8567df741c947c7c60afc9af71d16052937762c15bda9f0aa360/pandas-0.1.win32-py2.5.exe#sha256=1b25975c12ee09cb029d77dee1e6f500a6b88bc0cf995d72f3edd9b3c1d96eb0 (from https://pypi.org/simple/pandas/); unsupported archive format: .exe
```
(I removed the output regarding all versions from 0.2-0.24 due to github issue character limits)
```
    Skipping link https://files.pythonhosted.org/packages/ba/2b/84893a9f135831b2b49bdbb21ac96844a987877475ccff4e21b72d00ad1a/pandas-0.25.0rc0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=035ad4e2e12966fd69f47c8eecf37ae756753d5fbeba98a54b21b1f100bd2f89 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/e0/c0/e9fcd80669c3908c96f779db94896095a661e5c2180c61467b6a1df5accf/pandas-0.25.0rc0-cp35-cp35m-manylinux1_x86_64.whl#sha256=f7cfc35eccd977833e158064448c87c058837df193d526894dac74aabadb07cd (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/1f/ac/57bc224048592986a5aa57c19f26ce36f112d80b514473749def24a75966/pandas-0.25.0rc0-cp35-cp35m-win32.whl#sha256=19c3af208ea7632f1333b7ed328c8729aab1a1dc2e58a87a660b7d4edce965ff (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/19/b6/124914598447928889c6fe08a3e40ff791e1c66c7f6e3234374eefe38359/pandas-0.25.0rc0-cp35-cp35m-win_amd64.whl#sha256=ef9976c835d4a3f1de54b0d176711d27952b48cdf752b37fe60e69395fe35b9b (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/cb/57/c4bd1ab8315ab0ec4119e8134ef045ffef64f958dfb5cda013c02992fb74/pandas-0.25.0rc0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=e3bd9fb527073e663e225aa601bd846d40be8ad036f76a86ed3276c9c97fa04a (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/da/5b/881a701c7a0d440036ec238ff6b7b798029e9c0f6fb4728de3255c281749/pandas-0.25.0rc0-cp36-cp36m-manylinux1_i686.whl#sha256=d03a65a0566cb0bff9049f136b4a22981582ea045c17f3b9489f33dd59015daf (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/23/23/1795c54b1df0f4bbe1765f9b1c1602e6aa5ca87db9ce05baa3d654a023a0/pandas-0.25.0rc0-cp36-cp36m-manylinux1_x86_64.whl#sha256=c606c8f4431c816a23b9abe0bb7662bc388ae52817a894f3d46b5a0b63462d49 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/bd/cc/204bd0bce4433e5c5b26085d91f123f96e772ae7637cfde7663819934fce/pandas-0.25.0rc0-cp36-cp36m-win32.whl#sha256=87964be13bc108da3e7b98f122e902f32042cf370f627c631f296a69b08b2faa (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/65/3d/b521ad47476b6b615eb880380b231d95ebcaf28c89a849c41c0253d0d48d/pandas-0.25.0rc0-cp36-cp36m-win_amd64.whl#sha256=9693e42ed45bdeb8cd42c7b9ec9b2ca134e4f232eba3764f1e0adb42bdbc5648 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/d0/01/fe346ad5f3f5a19f7c061e493dee39fa680adcd9f3003196d209570c52c6/pandas-0.25.0rc0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=8f262ec14845e5da2890ac22a568b93aca12e8007218bc4dc55fea8827648d19 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/0e/a8/d34b513e409fa0f8e5e35edfeab55d0c090b3e6095b16182585a4a0e2709/pandas-0.25.0rc0-cp37-cp37m-manylinux1_x86_64.whl#sha256=71c5a3d0d013f5825e1c45aa79ecd2c7cce8d47f7544a5916804fd0406c7e0b7 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/64/30/951074ca2f27540fab444f44d6808db5b8045b85c23cd7e8ecc5c40f1cd7/pandas-0.25.0rc0-cp37-cp37m-win32.whl#sha256=db2c4ef8a622c1de2e8fed07792286d2f0cea31ce669c326f8bbe736f26eae47 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/3e/c5/efa1fc436dad4e8028af110bf2b661f42b981266311a9b65e11f3fd2b62f/pandas-0.25.0rc0-cp37-cp37m-win_amd64.whl#sha256=2028e57bb3242b3f53a5d80500e931c8b6fa987730e0309499b40f1895774c26 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/3e/a7/bfbaa1b8b2abc129793c329b37e69c54f5fd9a06f21a283ff91b17eaca73/pandas-0.25.0rc0.tar.gz#sha256=7fa6e3264009127c3b2c2dbd7257ec1301940c0bea0daae983d9d3ac0d7bb8a1 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3), version: 0.25.0rc0
    Skipping link https://files.pythonhosted.org/packages/44/a5/781eec04684eff461c5cd28421ac47666b359cd9b90fe0341841feb438b4/pandas-0.25.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=32c44e5b628c48ba17703f734d59f369d4cdcb4239ef26047d6c8a8bfda29a6b (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/a7/d9/e03b615e973c2733ff8fd53d95bd3633ecbfa81b5af2f83fe39647c02344/pandas-0.25.0-cp35-cp35m-manylinux1_x86_64.whl#sha256=df7e1933a0b83920769611c5d6b9a1bf301e3fa6a544641c6678c67621fe9843 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/94/43/2bb8b7bb69b36525b994ac1200c4bb4028730b626efbfe68c10c8958be52/pandas-0.25.0-cp35-cp35m-win32.whl#sha256=cfb862aa37f4dd5be0730731fdb8185ac935aba8b51bf3bd035658111c9ee1c9 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/07/f8/93e6d7ff91c3cdb3c45d4588cfc98815a457a5fe7ea4478829b2f6811402/pandas-0.25.0-cp35-cp35m-win_amd64.whl#sha256=b932b127da810fef57d427260dde1ad54542c136c44b227a1e367551bb1a684b (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/94/f0/3099fdb1ae94663561cd695b820f05b6f6d240c919ba179c076015de5e37/pandas-0.25.0-cp36-cp36m-macosx_10_9_x86_64.macosx_10_10_x86_64.whl#sha256=3b9f7dcee6744d9dcdd53bce19b91d20b4311bf904303fa00ef58e7df398e901 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/8f/17/14f74f9d06379d697912a508f3ed870335cbb500821ea866b1d19b5bf83a/pandas-0.25.0-cp36-cp36m-manylinux1_i686.whl#sha256=074a032f99bb55d178b93bd98999c971542f19317829af08c99504febd9e9b8b (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/1d/9a/7eb9952f4b4d73fbd75ad1d5d6112f407e695957444cb695cbb3cdab918a/pandas-0.25.0-cp36-cp36m-manylinux1_x86_64.whl#sha256=9023972a92073a495eba1380824b197ad1737550fe1c4ef8322e65fe58662888 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/52/4f/af4649ffd5082a3d6b6bf27b1508185e7dc2643c7f046fd3956b37c1a08f/pandas-0.25.0-cp36-cp36m-win32.whl#sha256=20f1728182b49575c2f6f681b3e2af5fac9e84abdf29488e76d569a7969b362e (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/6e/f6/7c5053cd6cae3ae099f4f950b9a5b4cb881432febdf2184f4b2d2d6de357/pandas-0.25.0-cp36-cp36m-win_amd64.whl#sha256=58f9ef68975b9f00ba96755d5702afdf039dea9acef6a0cfd8ddcde32918a79c (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/39/b7/441375a152f3f9929ff8bc2915218ff1a063a59d7137ae0546db616749f9/pandas-0.25.0-cp37-cp37m-macosx_10_9_x86_64.macosx_10_10_x86_64.whl#sha256=2745ba6e16c34d13d765c3657bb64fa20a0e2daf503e6216a36ed61770066179 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/3b/42/dc1f4820b95fbdbc9352ec9ad0f0c40db2122e1f2440ea53c7f9fbccf2b8/pandas-0.25.0-cp37-cp37m-manylinux1_x86_64.whl#sha256=9d151bfb0e751e2c987f931c57792871c8d7ff292bcdfcaa7233012c367940ee (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/22/1e/9eebae0a7e077301e54d73c6c510ecce6b648b843ed6b6d4eeddcd74022c/pandas-0.25.0-cp37-cp37m-win32.whl#sha256=de7ecb4b120e98b91e8a2a21f186571266a8d1faa31d92421e979c7ca67d8e5c (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/c1/cf/58ccaa38d5670dd4d2aee5df90aa03d670ede3947b7148e72391c80d4f91/pandas-0.25.0-cp37-cp37m-win_amd64.whl#sha256=544f2033250980fb6f069ce4a960e5f64d99b8165d01dc39afd0b244eeeef7d7 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/0b/1f/8fca0e1b66a632b62cc1ae38e197befe48c5cee78f895edf4bf8d340454d/pandas-0.25.0.tar.gz#sha256=914341ad2d5b1ea522798efa4016430b66107d05781dbfe7cf05eba8f37df995 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3), version: 0.25.0
  Using version 0.25.0 (newest of versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0)
  Created temporary directory: /tmp/pip-unpack-n2pd4kke
  Looking up "https://files.pythonhosted.org/packages/0b/1f/8fca0e1b66a632b62cc1ae38e197befe48c5cee78f895edf4bf8d340454d/pandas-0.25.0.tar.gz" in the cache
  No cache entry available
  Starting new HTTPS connection (1): files.pythonhosted.org:443
  https://files.pythonhosted.org:443 "GET /packages/0b/1f/8fca0e1b66a632b62cc1ae38e197befe48c5cee78f895edf4bf8d340454d/pandas-0.25.0.tar.gz HTTP/1.1" 200 12616848
  Downloading https://files.pythonhosted.org/packages/0b/1f/8fca0e1b66a632b62cc1ae38e197befe48c5cee78f895edf4bf8d340454d/pandas-0.25.0.tar.gz (12.6MB)
  Downloading from URL https://files.pythonhosted.org/packages/0b/1f/8fca0e1b66a632b62cc1ae38e197befe48c5cee78f895edf4bf8d340454d/pandas-0.25.0.tar.gz#sha256=914341ad2d5b1ea522798efa4016430b66107d05781dbfe7cf05eba8f37df995 (from https://pypi.org/simple/pandas/) (requires-python:>=3.5.3)
     |█████                           | 1.9MB 998kB/s eta 0:00:11^C
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-s667qpdr'
ERROR: Operation cancelled by user
Exception information:
Traceback (most recent call last):
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 347, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/download.py", line 886, in unpack_url
    progress_bar=progress_bar
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/download.py", line 746, in unpack_http_url
    progress_bar)
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/download.py", line 954, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/download.py", line 683, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/utils/hashes.py", line 62, in check_against_chunks
    for chunk in chunks:
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/download.py", line 651, in written_chunks
    for chunk in chunks:
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/utils/ui.py", line 158, in iter
    self.next(n)
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_vendor/progress/__init__.py", line 120, in next
    self.update()
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_vendor/progress/bar.py", line 80, in update
    suffix = self.suffix % self
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_vendor/progress/__init__.py", line 61, in __getitem__
    return getattr(self, key, None)
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/utils/ui.py", line 152, in pretty_eta
    return "eta %s" % self.eta_td
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_vendor/progress/__init__.py", line 147, in eta_td
    return timedelta(seconds=self.eta)
  File "/tmp/miniconda/envs/testenv/lib/python3.7/site-packages/pip/_internal/utils/ui.py", line 115, in handle_sigint
    self.original_handler(signum, frame)
KeyboardInterrupt
```

**Comment by mfeurer** [comment]
This fixed itself during the last few days.
