### ISSUE TITLE
Getting dataset from a task fails

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#760]
```
import openml

task_id = 3

task = openml.tasks.get_task(task_id)
X, y = task.get_X_and_y()
dataset = task.get_dataset()
```

error message:
```
Traceback (most recent call last):
  File "/home/janvanrijn/projects/openml-defaults/test.py", line 6, in <module>
    X, y = task.get_X_and_y()
  File "/home/janvanrijn/anaconda3/envs/openml-defaults/lib/python3.7/site-packages/openml/tasks/task.py", line 76, in get_X_and_y
    X_and_y = dataset.get_data(target=self.target_name)
  File "/home/janvanrijn/anaconda3/envs/openml-defaults/lib/python3.7/site-packages/openml/datasets/dataset.py", line 377, in get_data
    x = data[:, ~targets]
  File "/home/janvanrijn/anaconda3/envs/openml-defaults/lib/python3.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/janvanrijn/anaconda3/envs/openml-defaults/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 110, in pandas._libs.index.IndexEngine.get_loc
TypeError: '(slice(None, None, None), array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False]))' is an invalid key
```

pip freeze tells 
```
openml==0.8.0
```

**Comment by janvanrijn** [comment]
Seems that this function is deleted from the current development branch. Any specific reason for this? Is there an alternative?

**Comment by janvanrijn** [comment]
Seems that it depends on the task type. 

As this specific problem (but a different one) does not occur in the development branch, let's close.
