### ISSUE TITLE
list_evaluations_setups to have complicated setup obtain mechanism

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#794]
IMO this code can be simplified by relying on the pagination function of the general listing function? 

This avoids having duplicate complicated code blocks 

(note that there are a lot of testing functions keeping the pagination function of listing working)

**Comment by janvanrijn** [comment]
It also fails:

```
import openml

evals = openml.evaluations.list_evaluations_setups('predictive_accuracy', flow=[7707], task=[3], size=1000, output_format='dataframe')
```

Traceback:
```
/home/janvanrijn/anaconda3/envs/openml-pimp/bin/python /home/janvanrijn/projects/openml-python/test.py
Traceback (most recent call last):
  File "/home/janvanrijn/anaconda3/envs/openml-pimp/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 843, in split
    len(indices_or_sections)
TypeError: object of type 'int' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/janvanrijn/projects/openml-python/test.py", line 3, in <module>
    evals = openml.evaluations.list_evaluations_setups('predictive_accuracy', flow=[7707], task=[3], size=1000, output_format='dataframe')
  File "/home/janvanrijn/projects/openml-python/openml/evaluations/functions.py", line 334, in list_evaluations_setups
    ((len(evals['setup_id'].unique()) - 1) // N) + 1)
  File "/home/janvanrijn/anaconda3/envs/openml-pimp/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 849, in split
    'array split does not result in an equal division')
ValueError: array split does not result in an equal division
```

**Comment by sahithyaravi1493** [comment]
@janvanrijn this issue has been addressed here https://github.com/openml/openml-python/issues/838

**Comment by mfeurer** [comment]
Closing this. please reopen @janvanrijn if this still is an issue
