### ISSUE TITLE
TypeError: Dataset features require attribute `nominal_values` for nominal feature type.

### ISSUE THREAD

**Issue by FelixNeutatz** [openml/openml-python#904]
#### Description
Dear all,
I want to download a quite famous dataset using OpenML but I always get an exception:
Any help would be appreciated :)

Best regards,
Felix

#### Steps/Code to Reproduce

Example:
```python
import openml
print(openml.__version__)
openml.datasets.get_dataset(31)
```

#### Expected Results
No error

#### Actual Results
```
0.10.2
Traceback (most recent call last):
  File "/home/felix/FastFeatures/new_project/fastsklearnfeature/interactiveAutoML/new_bench/multiobjective/metalearning/openml_data/check_data_stats.py", line 38, in <module>
    openml.datasets.get_dataset(31)
  File "/home/felix/anaconda/envs/new_project/lib/python3.7/site-packages/openml/utils.py", line 356, in safe_func
    return func(*args, **kwargs)
  File "/home/felix/anaconda/envs/new_project/lib/python3.7/site-packages/openml/datasets/functions.py", line 530, in get_dataset
    description, features, qualities, arff_file
  File "/home/felix/anaconda/envs/new_project/lib/python3.7/site-packages/openml/datasets/functions.py", line 1023, in _create_dataset_from_description
    qualities=qualities,
  File "/home/felix/anaconda/envs/new_project/lib/python3.7/site-packages/openml/datasets/dataset.py", line 174, in __init__
    int(nr_missing))
  File "/home/felix/anaconda/envs/new_project/lib/python3.7/site-packages/openml/datasets/data_feature.py", line 31, in __init__
    raise TypeError('Dataset features require attribute `nominal_values` for nominal '
TypeError: Dataset features require attribute `nominal_values` for nominal feature type.
```

#### Versions
0.10.2

**Comment by PGijsbers** [comment]
Sorry for the late reply. I am currently unable to reproduce this behavior. Could you try removing the old cache directory (something like `~/.openml/cache/org/openml/www/datasets/31/`), and try this again?

**Comment by FelixNeutatz** [comment]
Yes, "sudo rm -rf .openml" solved the issue :)
